/**
 * Test preload script: ensures generated files exist before any tests run,
 * and applies the suite-wide test timeout.
 *
 * When `bun test` is invoked directly (instead of `bun run test` which runs
 * npm scripts first), generated files like src/version.ts and lazy-agent may
 * be missing — especially in git worktrees where gitignored files aren't
 * present. This preload generates them so tests can import src/index.ts.
 */
import { existsSync, readFileSync, writeFileSync, renameSync } from 'fs';
import { join } from 'path';
import { setDefaultTimeout } from 'bun:test';

// bunfig.toml's `[test] timeout` is NOT honored by the bun we run on — every
// test silently got bun's 5s default instead of the configured 30s. That is
// under the wall-clock of an ordinary e2e test (start + reconcile + accept is
// several seconds), so suites failed with bare "timed out after 5000ms" that
// look like hangs and aren't. setDefaultTimeout IS honored; per-test overrides
// (`test(..., 15000)`) still win over it.
setDefaultTimeout(30_000);

// Hermetic model credential for the TEST PROCESS itself.
//
// The daemon credential gate now runs inside startDaemonServer(), and several
// e2e suites call that function in-process rather than through the CLI. Without
// this, whether those tests pass would depend on whether the developer happens
// to have a credential exported — green on a dev laptop, red in CI. Agent calls
// are always mocked, so a fake key is exactly as good as a real one here.
//
// The real OAuth token (if the developer has one) is removed for the same
// reason: the test process must behave identically everywhere. Tests that
// exercise the gate's REFUSAL clear these explicitly in the subprocess env they
// pass to ctx.lazy(), so this does not weaken them.
delete process.env.CLAUDE_CODE_OAUTH_TOKEN;
process.env.ANTHROPIC_API_KEY = 'sk-test-fake-key-for-testing';

// Arm the stray-daemon safety net for the whole test process. Importing the
// module installs its exit/SIGINT/SIGTERM handlers so daemons spawned by any
// test are reaped even if that test's afterEach never runs.
import './helpers/daemon-registry';

const root = join(import.meta.dir, '..');

// Generate src/version.ts if missing. The version STRING is computed by the
// same module the real generator uses — this file used to carry its own copy of
// the logic, which then silently drifted from it.
const versionPath = join(root, 'src', 'version.ts');
if (!existsSync(versionPath)) {
  const { computeVersion } = require('../scripts/version-string');
  writeFileSync(versionPath, `// Auto-generated by scripts/generate-version.ts — do not edit manually\nexport const VERSION = '${computeVersion(root)}';\n`);
}

// Generate src/build-info.ts — tests import it (transitively via the daemon
// status path) and there is no compile step in tests, so dev defaults apply.
//
// Rewritten whenever it does NOT match the dev template, not merely when absent.
// The file is gitignored, and `scripts/build.ts` stamps real metadata into it;
// once anything has built in a worktree, that stamp persists and daemon.test.ts's
// dev-default assertion is red forever in that worktree for a reason unrelated
// to the code. Tests own this file's contents while they run; the next build
// regenerates it.
const { DEV_BUILD_INFO } = require('../scripts/build-info-content');
const buildInfoPath = join(root, 'src', 'build-info.ts');
if (!existsSync(buildInfoPath) || readFileSync(buildInfoPath, 'utf-8') !== DEV_BUILD_INFO) {
  // Atomic, for the same reason as the prompt bundle below: an e2e run has many
  // CLI subprocesses importing this module while one may be rewriting it.
  const tmp = `${buildInfoPath}.${process.pid}.tmp`;
  writeFileSync(tmp, DEV_BUILD_INFO);
  renameSync(tmp, buildInfoPath);
}

// Generate src/prompts-bundle.ts for test/unit/prompt-bundle.test.ts, which
// imports it statically, and for typecheck. src/ itself loads it only in a
// compiled binary, so a stale bundle no longer breaks the CLI — but the bundle
// is gitignored, so a fresh worktree has none until something generates it.
//
// Regenerated when MISSING or STALE, not just when missing. Because the bundle
// is gitignored, a worktree keeps whichever copy it generated first — so
// merging a branch that adds a prompt leaves the bundle a file short, and
// prompt-bundle.test.ts fails with a drift error on a machine whose code is
// perfectly fine. The generator is cheap and writes atomically, so the
// staleness check costs one stat per prompt and cannot tear a concurrent read.
{
  const { generatePromptBundle, isPromptBundleStale } = require('../scripts/generate-prompt-bundle');
  if (isPromptBundleStale()) generatePromptBundle();
}

// Ensure lazy-agent placeholder exists (needed for `import ... with { type: 'file' }`)
const agentPath = join(root, 'lazy-agent');
if (!existsSync(agentPath)) {
  writeFileSync(agentPath, 'placeholder\n');
}
