/**
 * Test preload script: ensures generated files exist before any tests run.
 *
 * When `bun test` is invoked directly (instead of `bun run test` which runs
 * npm scripts first), generated files like src/version.ts and lazy-agent may
 * be missing — especially in git worktrees where gitignored files aren't
 * present. This preload generates them so tests can import src/index.ts.
 */
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';

// Arm the stray-daemon safety net for the whole test process. Importing the
// module installs its exit/SIGINT/SIGTERM handlers so daemons spawned by any
// test are reaped even if that test's afterEach never runs.
import './helpers/daemon-registry';

const root = join(import.meta.dir, '..');

// Generate src/version.ts if missing
const versionPath = join(root, 'src', 'version.ts');
if (!existsSync(versionPath)) {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
  let version = pkg.version;
  try {
    const commitCount = execSync('git rev-list --count HEAD', {
      cwd: root,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    if (/^\d+$/.test(commitCount)) {
      const [major, minor] = pkg.version.split('.');
      version = `${major}.${minor}.${commitCount}`;
    }
  } catch {
    // Git not available — use package.json version as-is
  }
  writeFileSync(versionPath, `// Auto-generated by scripts/generate-version.ts — do not edit manually\nexport const VERSION = '${version}';\n`);
}

// Generate src/build-info.ts if missing — tests import it (transitively via the
// daemon status path) and there is no compile step in tests, so BUILD_TIME='dev'.
const buildInfoPath = join(root, 'src', 'build-info.ts');
if (!existsSync(buildInfoPath)) {
  writeFileSync(buildInfoPath, `// Auto-generated by scripts/generate-version.ts / scripts/build.ts — do not edit manually\nexport const BUILD_TIME = 'dev';\n`);
}

// Ensure lazy-agent placeholder exists (needed for `import ... with { type: 'file' }`)
const agentPath = join(root, 'lazy-agent');
if (!existsSync(agentPath)) {
  writeFileSync(agentPath, 'placeholder\n');
}
