/**
 * Test preload script: ensures generated files exist before any tests run,
 * and applies the suite-wide test timeout.
 *
 * When `bun test` is invoked directly (instead of `bun run test` which runs
 * npm scripts first), generated files like src/version.ts and lazy-agent may
 * be missing — especially in git worktrees where gitignored files aren't
 * present. This preload generates them so tests can import src/index.ts.
 */
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import { setDefaultTimeout } from 'bun:test';

// bunfig.toml's `[test] timeout` is NOT honored by the bun we run on — every
// test silently got bun's 5s default instead of the configured 30s. That is
// under the wall-clock of an ordinary e2e test (start + reconcile + accept is
// several seconds), so suites failed with bare "timed out after 5000ms" that
// look like hangs and aren't. setDefaultTimeout IS honored; per-test overrides
// (`test(..., 15000)`) still win over it.
setDefaultTimeout(30_000);

// Hermetic model credential for the TEST PROCESS itself.
//
// The daemon credential gate now runs inside startDaemonServer(), and several
// e2e suites call that function in-process rather than through the CLI. Without
// this, whether those tests pass would depend on whether the developer happens
// to have a credential exported — green on a dev laptop, red in CI. Agent calls
// are always mocked, so a fake key is exactly as good as a real one here.
//
// The real OAuth token (if the developer has one) is removed for the same
// reason: the test process must behave identically everywhere. Tests that
// exercise the gate's REFUSAL clear these explicitly in the subprocess env they
// pass to ctx.lazy(), so this does not weaken them.
delete process.env.CLAUDE_CODE_OAUTH_TOKEN;
process.env.ANTHROPIC_API_KEY = 'sk-test-fake-key-for-testing';

// Arm the stray-daemon safety net for the whole test process. Importing the
// module installs its exit/SIGINT/SIGTERM handlers so daemons spawned by any
// test are reaped even if that test's afterEach never runs.
import './helpers/daemon-registry';

const root = join(import.meta.dir, '..');

// Generate src/version.ts if missing
const versionPath = join(root, 'src', 'version.ts');
if (!existsSync(versionPath)) {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
  let version = pkg.version;
  try {
    const commitCount = execSync('git rev-list --count HEAD', {
      cwd: root,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    if (/^\d+$/.test(commitCount)) {
      const [major, minor] = pkg.version.split('.');
      version = `${major}.${minor}.${commitCount}`;
    }
  } catch {
    // Git not available — use package.json version as-is
  }
  writeFileSync(versionPath, `// Auto-generated by scripts/generate-version.ts — do not edit manually\nexport const VERSION = '${version}';\n`);
}

// Generate src/build-info.ts if missing — tests import it (transitively via the
// daemon status path) and there is no compile step in tests, so BUILD_TIME='dev'.
const buildInfoPath = join(root, 'src', 'build-info.ts');
if (!existsSync(buildInfoPath)) {
  writeFileSync(buildInfoPath, `// Auto-generated by scripts/generate-version.ts / scripts/build.ts — do not edit manually\nexport const BUILD_TIME = 'dev';\n`);
}

// Generate src/prompts-bundle.ts if missing — src/cli/commands/prompts.ts
// imports PROMPT_BUNDLE from it, and that path is pulled in transitively when
// tests import src/index.ts. It's gitignored (regenerated on every dev/build/
// prepare run), so in a fresh worktree with no build step it's absent and the
// import fails module resolution CLI-wide. Regenerate it here for the same
// reason version.ts/build-info.ts are generated above.
const promptBundlePath = join(root, 'src', 'prompts-bundle.ts');
if (!existsSync(promptBundlePath)) {
  const { generatePromptBundle } = require('../scripts/generate-prompt-bundle');
  generatePromptBundle();
}

// Ensure lazy-agent placeholder exists (needed for `import ... with { type: 'file' }`)
const agentPath = join(root, 'lazy-agent');
if (!existsSync(agentPath)) {
  writeFileSync(agentPath, 'placeholder\n');
}
