/**
 * Build provenance: capture git identity at compile time and format it for
 * human-facing output (`lazy upgrade`, `lazy --version`, `lazy-agent selfcheck`).
 */

import { homedir } from 'os';
import { detectBranch } from '../../scripts/version-string';
import { spawnSyncUnsupervised } from './spawn';

/** Git probes during provenance capture should finish quickly or fall back. */
const GIT_PROBE_TIMEOUT_MS = 5_000;

export interface BuildInfoValues {
  /** UTC ISO timestamp, or 'dev' when there is no compile step. */
  buildTime: string;
  /** Git short SHA at build time, 'dev' in source runs, 'unknown' when git fails. */
  buildSha: string;
  /** True when the working tree had uncommitted changes at build time. */
  buildDirty: boolean;
  /** Branch checked out at build time, 'dev' in source runs, 'unknown' when git fails. */
  buildBranch: string;
  /** Absolute source checkout path at build time, 'dev' in source runs. */
  buildSourcePath: string;
}

/** Values used for `bun run ./src/index.ts`, tests, and `generate:version`. */
export const DEV_BUILD_INFO_VALUES: BuildInfoValues = {
  buildTime: 'dev',
  buildSha: 'dev',
  buildDirty: false,
  buildBranch: 'dev',
  buildSourcePath: 'dev',
};

function escapeBuildInfoString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

export function formatBuildInfoContent(values: BuildInfoValues): string {
  return `// Auto-generated by scripts/generate-version.ts / scripts/build.ts — do not edit manually
export const BUILD_TIME = '${escapeBuildInfoString(values.buildTime)}';
export const BUILD_SHA = '${escapeBuildInfoString(values.buildSha)}';
export const BUILD_DIRTY = ${values.buildDirty};
export const BUILD_BRANCH = '${escapeBuildInfoString(values.buildBranch)}';
export const BUILD_SOURCE_PATH = '${escapeBuildInfoString(values.buildSourcePath)}';
`;
}

/** Full file contents for the dev/test default build-info module. */
export const DEV_BUILD_INFO = formatBuildInfoContent(DEV_BUILD_INFO_VALUES);

/**
 * Capture git identity at build time. Called BEFORE writing build-info.ts so
 * the file we are about to stamp does not itself flip the dirty bit.
 */
export function captureGitBuildMetadata(projectRoot: string): Pick<BuildInfoValues, 'buildSha' | 'buildDirty'> {
  let buildSha = 'unknown';
  let buildDirty = false;

  const shaProc = spawnSyncUnsupervised(['git', 'rev-parse', '--short', 'HEAD'], {
    cwd: projectRoot,
    stdout: 'pipe',
    stderr: 'pipe',
    timeout: GIT_PROBE_TIMEOUT_MS,
  });
  const shaOut = shaProc.stdout.toString().trim();
  if (shaProc.exitCode === 0 && shaOut) {
    buildSha = shaOut;
  }

  const dirtyProc = spawnSyncUnsupervised(['git', 'status', '--porcelain'], {
    cwd: projectRoot,
    stdout: 'pipe',
    stderr: 'pipe',
    timeout: GIT_PROBE_TIMEOUT_MS,
  });
  if (dirtyProc.exitCode === 0) {
    buildDirty = dirtyProc.stdout.toString().trim().length > 0;
  }

  return { buildSha, buildDirty };
}

/**
 * Resolve the branch name for provenance display.
 *
 * Uses the same CI-first branch detection as version-string.ts. When git is on
 * a detached HEAD (common in CI), falls back to `git name-rev` so the label is
 * still informative rather than the literal string `HEAD`.
 */
export function resolveBuildBranch(projectRoot: string): string {
  const fromDetect = detectBranch(projectRoot);
  if (fromDetect) return fromDetect;

  const branchProc = spawnSyncUnsupervised(['git', 'branch', '--show-current'], {
    cwd: projectRoot,
    stdout: 'pipe',
    stderr: 'pipe',
    timeout: GIT_PROBE_TIMEOUT_MS,
  });
  const branch = branchProc.stdout.toString().trim();
  if (branchProc.exitCode === 0 && branch) return branch;

  const nameRevProc = spawnSyncUnsupervised(['git', 'name-rev', '--name-only', 'HEAD'], {
    cwd: projectRoot,
    stdout: 'pipe',
    stderr: 'pipe',
    timeout: GIT_PROBE_TIMEOUT_MS,
  });
  const nameRev = nameRevProc.stdout.toString().trim();
  if (nameRevProc.exitCode === 0 && nameRev && nameRev !== 'undefined') {
    return nameRev
      .replace(/^remotes\/origin\//, '')
      .replace(/^tags\//, '');
  }

  return 'detached';
}

/**
 * Capture full build provenance for a source checkout.
 *
 * Called BEFORE writing build-info.ts so the write itself does not flip dirty.
 */
export function captureBuildProvenance(projectRoot: string): BuildInfoValues {
  const { buildSha, buildDirty } = captureGitBuildMetadata(projectRoot);
  return {
    buildTime: new Date().toISOString(),
    buildSha,
    buildDirty,
    buildBranch: resolveBuildBranch(projectRoot),
    buildSourcePath: projectRoot,
  };
}

/** Shorten an absolute path with a leading `~` when it lives under $HOME. */
export function formatDisplayPath(absPath: string): string {
  if (absPath === 'dev') return absPath;
  const home = process.env.HOME || homedir();
  if (absPath === home) return '~';
  if (absPath.startsWith(home + '/')) return '~' + absPath.slice(home.length);
  return absPath;
}

/** Human line for upgrade / ensureAgentBinary: `built from ~/path @ branch (sha, clean)`. */
export function formatSourceProvenanceLine(
  provenance: Pick<BuildInfoValues, 'buildSourcePath' | 'buildBranch' | 'buildSha' | 'buildDirty'>,
): string {
  const path = formatDisplayPath(provenance.buildSourcePath);
  const branch = provenance.buildBranch || 'unknown';
  const dirtyLabel = provenance.buildDirty ? 'dirty' : 'clean';
  return `built from ${path} @ ${branch} (${provenance.buildSha}, ${dirtyLabel})`;
}

/**
 * Suffix for `lazy --version` / `lazy-agent selfcheck` when build metadata was
 * embedded at compile time. Empty for dev defaults (source runs without compile).
 */
export function formatEmbeddedBuildProvenance(
  provenance: Pick<BuildInfoValues, 'buildBranch' | 'buildSha' | 'buildDirty' | 'buildSourcePath'>,
): string {
  if (provenance.buildSha === 'dev' || provenance.buildSha === 'unknown') return '';

  const path = formatDisplayPath(provenance.buildSourcePath);
  const branch = provenance.buildBranch && provenance.buildBranch !== 'dev'
    ? provenance.buildBranch
    : null;
  const dirtyLabel = provenance.buildDirty ? 'dirty' : 'clean';

  if (branch && branch !== 'unknown' && branch !== 'detached') {
    return ` (${branch}@${provenance.buildSha}, ${dirtyLabel}, ${path})`;
  }
  return ` (${provenance.buildSha}, ${dirtyLabel}, ${path})`;
}

/** Success line for `lazy upgrade`'s agent-binary rebuild step. */
export function formatAgentBinaryRebuildSuccessLine(
  provenance: Pick<BuildInfoValues, 'buildSourcePath' | 'buildBranch' | 'buildSha' | 'buildDirty'> | null,
): string {
  const base = 'rebuilt agent binary (verified)';
  if (!provenance) return base;
  return `${base} — ${formatSourceProvenanceLine(provenance)}`;
}

/** Read compile-time build metadata from the generated module, when present. */
export async function readEmbeddedBuildProvenance(): Promise<Pick<
  BuildInfoValues,
  'buildBranch' | 'buildSha' | 'buildDirty' | 'buildSourcePath'
> | null> {
  try {
    const mod = await import('../build-info');
    return {
      buildBranch: mod.BUILD_BRANCH ?? 'dev',
      buildSha: mod.BUILD_SHA ?? 'dev',
      buildDirty: mod.BUILD_DIRTY ?? false,
      buildSourcePath: mod.BUILD_SOURCE_PATH ?? 'dev',
    };
  } catch {
    return null;
  }
}

/** Append embedded provenance to a version/selfcheck line when available. */
export async function formatVersionWithEmbeddedProvenance(version: string): Promise<string> {
  const provenance = await readEmbeddedBuildProvenance();
  if (!provenance) return version;
  const suffix = formatEmbeddedBuildProvenance(provenance);
  return suffix ? `${version}${suffix}` : version;
}

/** Human-readable `Built:` value for `lazy daemon status`. */
export function formatDaemonBuiltLine(
  status: Partial<Pick<BuildInfoValues, 'buildTime' | 'buildSha' | 'buildDirty' | 'buildBranch' | 'buildSourcePath'>>,
): string | null {
  if (!status.buildTime) return null;
  if (status.buildTime === 'dev') return 'dev';

  let line = `${status.buildTime} (UTC)`;
  if (status.buildSha && status.buildSha !== 'dev') {
    line += ` at ${status.buildSha}`;
    if (status.buildDirty) line += ' (dirty tree)';
  }

  const branch = status.buildBranch && status.buildBranch !== 'dev' ? status.buildBranch : null;
  const path = status.buildSourcePath && status.buildSourcePath !== 'dev'
    ? formatDisplayPath(status.buildSourcePath)
    : null;
  if (branch || path) {
    const parts: string[] = [];
    if (branch && branch !== 'unknown') parts.push(`branch ${branch}`);
    if (path) parts.push(`from ${path}`);
    if (parts.length > 0) line += ` — ${parts.join(', ')}`;
  }

  return line;
}
