/**
 * Local-command scaffolding — the predicate for "this message is Claude Code's own
 * harness noise, not something anyone said".
 *
 * WHY THIS EXISTS
 * ---------------
 * When a human runs a BUILT-IN slash command (`/clear`, `/model`, `/compact`,
 * `/context`, …), Claude Code journals the interaction into the session JSONL as
 * ordinary user messages:
 *
 *   1. a fixed caveat telling the model to ignore what follows —
 *      `<local-command-caveat>Caveat: The messages below were generated by the user
 *      while running local commands. DO NOT respond…</local-command-caveat>`
 *   2. the invocation itself —
 *      `<command-name>/clear</command-name> <command-message>clear</command-message>
 *      <command-args></command-args>`
 *   3. whatever the command printed — `<local-command-stdout>Set model to `Fable
 *      5.1`…</local-command-stdout>` (and the `-stderr` twin)
 *
 * None of that is conversation. A session that is ONLY this — the common case, since
 * `/clear` starts a fresh JSONL and typing `/clear` again immediately ends it — has no
 * human intent and no agent reasoning in it at all, yet it was stored, listed and
 * searched like any other conversation. Sessions that DO go on to hold a real
 * conversation were showing the caveat as their listing summary, because the summary is
 * the first user message.
 *
 * WHERE THE LINE IS DRAWN
 * -----------------------
 * Import paths are mechanistic: they bring content in verbatim and never curate. So the
 * rule is narrow and structural — a message is dropped only when it consists ENTIRELY of
 * these wrappers and therefore contains no human-authored payload:
 *
 *   - `<command-args>` with anything in it is KEPT. `/compact keep awareness on last
 *     night's run` is text the human typed; the wrapper around it does not make it
 *     scaffolding.
 *   - a message that merely QUOTES a wrapper is KEPT — someone discussing this very
 *     behaviour writes the caveat into a real message, and that message is real.
 *
 * Matching is on Claude Code's own tags, never on the caveat's prose ("Caveat: The
 * messages below…"), for the same reason `machine-oneshot.ts` refuses to match on prompt
 * wording: wording is reworded, and the check would silently rot. If Claude Code ever
 * emits an untagged caveat, that variant is simply not matched and the message is kept —
 * the safe direction, exactly as an unreadable file is treated as a real session there.
 *
 * A conversation left with no messages after this filtering is skipped by the
 * "no parseable messages" guard every ingest path already has (capture-session,
 * capture-sweep, reimport-conversations), so nothing extra is needed to stop it being
 * stored.
 */

/**
 * The wrapper elements a message may be made of and still be scaffolding. Each is
 * anchored at the current scan position; `<command-args>` is deliberately restricted to
 * the EMPTY form.
 */
const SCAFFOLDING_ELEMENTS: RegExp[] = [
  /^<local-command-caveat>[\s\S]*?<\/local-command-caveat>/,
  /^<local-command-stdout>[\s\S]*?<\/local-command-stdout>/,
  /^<local-command-stderr>[\s\S]*?<\/local-command-stderr>/,
  /^<command-name>[\s\S]*?<\/command-name>/,
  /^<command-message>[\s\S]*?<\/command-message>/,
  /^<command-args>\s*<\/command-args>/,
];

/**
 * Claude Code's own HOUSEKEEPING slash commands — the ones this filter was
 * written for and verified against.
 *
 * WHY A LIST, rather than "anything with a `<command-name>`": a PROJECT or
 * CUSTOM command invoked without arguments produces exactly the same tag shape
 * as `/clear` — `<command-name>` plus `<command-message>` plus an EMPTY
 * `<command-args>` — so the shape alone cannot tell "the user tidied the
 * session" from "the user ran the command that explains the next fifty
 * messages". Every invocation recorded in this project's store has empty args,
 * so shape-only matching would drop every custom invocation too.
 *
 * Whether that costs real CONTENT depends on something not verifiable from a
 * task container: if Claude Code writes a custom command's expanded prompt as a
 * separate user message, only the "which command produced this" label is lost;
 * if the expansion rides in the same message, substance is lost. This list
 * makes the filter correct under BOTH readings — an unrecognised command is
 * kept either way — which is the same safe direction the module already takes
 * for an untagged caveat.
 *
 * An INCOMPLETE list therefore fails harmlessly: a housekeeping command missing
 * from it is kept as a small stub, never dropped content. Add names here when
 * that stub becomes annoying; never widen this to "any command name".
 */
const HOUSEKEEPING_COMMANDS = new Set([
  'add-dir', 'agents', 'bug', 'clear', 'compact', 'config', 'context', 'cost',
  'doctor', 'exit', 'export', 'feedback', 'help', 'hooks', 'ide', 'init',
  'install-github-app', 'login', 'logout', 'mcp', 'memory', 'migrate-installer',
  'model', 'output-style', 'permissions', 'pr-comments', 'privacy-settings',
  'release-notes', 'resume', 'status', 'statusline', 'terminal-setup', 'todos',
  'upgrade', 'vim',
]);

/** The command a `<command-name>` names, without its leading slash, lowercased. */
function commandNameIn(text: string): string | null {
  const m = /<command-name>\s*\/?([^<\s]*)\s*<\/command-name>/.exec(text);
  return m ? (m[1] ?? '').toLowerCase() : null;
}

/**
 * Is this one of Claude Code's built-in housekeeping commands?
 *
 * Exported for the doctor CHECK (`summaryLooksLikeScaffolding`), which must
 * stay a strict subset of what the remedy acts on: without this the check would
 * flag a custom command's summary that the remedy now deliberately keeps.
 */
export function isHousekeepingCommandName(name: string): boolean {
  return HOUSEKEEPING_COMMANDS.has(name.trim().replace(/^\//, '').toLowerCase());
}

/**
 * Is this message text nothing but Claude Code local-command scaffolding?
 *
 * Consumes wrapper elements (and the whitespace Claude Code indents them with) from the
 * front of the text; true only if the whole message is consumed that way. Anything left
 * over — prose, a non-empty `<command-args>`, an unrecognised tag — means the message
 * carries content and is kept.
 *
 * A message naming a command that is not in {@link HOUSEKEEPING_COMMANDS} is kept
 * whatever its shape: see that list for why the tag shape alone cannot decide it.
 */
export function isLocalCommandScaffolding(text: string): boolean {
  let rest = text.trim();
  if (!rest) return false;

  // A named command decides it before any shape matching: only the built-in
  // housekeeping set is noise. A message with no `<command-name>` at all (a
  // bare caveat, a stdout block) falls through to the shape rules below.
  const named = commandNameIn(rest);
  if (named !== null && !HOUSEKEEPING_COMMANDS.has(named)) return false;

  let consumedAny = false;
  while (rest) {
    const match = SCAFFOLDING_ELEMENTS.reduce<RegExpMatchArray | null>(
      (found, re) => found ?? rest.match(re),
      null,
    );
    if (!match) return false;
    consumedAny = true;
    rest = rest.slice(match[0].length).trim();
  }

  return consumedAny;
}
