#!/usr/bin/env bun
/**
 * Build script for lazy.
 *
 * Runs `bun build --compile` from a temp directory to work around a Bun bug
 * where the compiler creates a temp file in CWD and then fails to rename it
 * on certain filesystems (virtiofs mounts in Docker on macOS, and some
 * macOS APFS configurations).
 *
 * The output is also written to the temp directory first and then copied to
 * the final destination, avoiding issues with cross-filesystem writes.
 */
import { join, basename } from 'path';
import { mkdtempSync, rmSync, copyFileSync, existsSync, unlinkSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';

const projectRoot = join(import.meta.dir, '..');

// Embed the real build timestamp (UTC) so `lazy daemon status` can report when
// the running binary was built. generate-version.ts writes 'dev' for non-build
// contexts; we overwrite it here with the actual time so it's baked into the
// compiled binary below. Mirrors how VERSION is embedded via src/version.ts.
const buildTime = new Date().toISOString();
writeFileSync(
  join(projectRoot, 'src', 'build-info.ts'),
  `// Auto-generated by scripts/generate-version.ts / scripts/build.ts — do not edit manually\nexport const BUILD_TIME = '${buildTime}';\n`,
);
console.log(`Embedding build time: ${buildTime}`);

function getLinuxArch(): string {
  const arch = process.arch; // 'x64', 'arm64', etc.
  return arch === 'arm64' ? 'arm64' : 'x64';
}

/**
 * Run bun build --compile from a temp directory to avoid filesystem rename issues.
 * Compiles to the temp dir first, then copies the result to the final destination.
 */
/**
 * Flags that make a build a RELEASE build, in the security sense.
 *
 * `--define LAZY_RELEASE_BUILD=true` turns the test-only prompt seams in
 * src/cli/editor.ts (LAZY_FORCE_TTY, LAZY_PROMPT_DEFAULTS, LAZY_PROMPT_SECRET)
 * into dead code, and `--minify-syntax` is what actually removes it — without
 * it bun folds the constant but keeps the branch. Together they mean a released
 * binary has no environment-variable route to auto-answering a prompt, which
 * matters most for the approval passphrase `lazy approve` demands on a
 * protected merge: a runtime check would be one an agent could satisfy too.
 *
 * EXACTLY ONE THIRD OF `--minify` IS ENABLED, ON PURPOSE. `--minify` is
 * `--minify-syntax` + `--minify-whitespace` + `--minify-identifiers`:
 *
 * - syntax        constant folding and dead-code elimination — the half that
 *                 removes the seams, and the only half we want.
 * - identifiers   renames functions and variables, so a stack trace from a
 *                 released binary names `t` instead of `approveTaskPreflight`.
 * - whitespace    collapses everything onto few lines, so the line numbers in
 *                 that trace stop pointing anywhere useful.
 *
 * A released binary's stack traces are how a user's bug report becomes
 * actionable, so enabling either of the other two later is a regression in
 * exchange for a smaller file — not a trade worth making here.
 *
 * test/unit/build-release-flags.test.ts fails if either flag disappears.
 */
const RELEASE_DEFINES = ['--define', 'LAZY_RELEASE_BUILD=true', '--minify-syntax'];

function bunCompile(args: string[], finalOutfile: string): void {
  const tempDir = mkdtempSync(join(tmpdir(), 'lazy-build-'));
  const tempOutfile = join(tempDir, basename(finalOutfile));
  try {
    const proc = Bun.spawnSync(['bun', 'build', '--compile', ...RELEASE_DEFINES, ...args, '--outfile', tempOutfile], {
      cwd: tempDir,
      stdout: 'inherit',
      stderr: 'inherit',
      env: process.env,
    });
    if (proc.exitCode !== 0) {
      throw new Error(`bun build failed with exit code ${proc.exitCode}`);
    }
    copyFileSync(tempOutfile, finalOutfile);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

// Build agent binary (cross-compiled for Linux)
const agentEntry = join(projectRoot, 'src', 'agent-entry.ts');
const agentOutfile = join(projectRoot, 'lazy-agent');
const linuxTarget = `bun-linux-${getLinuxArch()}`;

// Overwrite existing binaries before building to prevent bun from creating
// massive sparse temp files (150GB+) when the target already exists.
// Even if the binary doesn't exist, we have to have a placeholder to solve
// the circular dependency (will be fixed sometime later)
writeFileSync(agentOutfile, 'placeholder');

console.log(`Building agent binary for ${linuxTarget}...`);
bunCompile([`--target=${linuxTarget}`, agentEntry], agentOutfile);

// Build host binary (native)
const hostEntry = join(projectRoot, 'src', 'index.ts');
const hostOutfile = join(projectRoot, 'lazy');

if (existsSync(hostOutfile)) unlinkSync(hostOutfile);

console.log('Building host binary...');
bunCompile([hostEntry], hostOutfile);

console.log('Build complete.');
