#!/usr/bin/env bun
/**
 * Generates src/prompts-bundle.ts — a static map of every top-level built-in
 * prompt (src/prompts/*.md) keyed by filename.
 *
 * WHY: `lazy system prompts` and `lazy show <prompt-code>` list/read built-in
 * prompts. In dev (`bun run ./src/index.ts`) they read the real files from
 * src/prompts/ so edits are instantly visible. In a compiled binary
 * (`bun build --compile`) there is no src/prompts/ directory on disk, so the
 * command would find nothing. This generated module uses Bun text imports
 * (`import x from './prompts/foo.md' with { type: 'text' }`) which the compiler
 * inlines into the binary, giving compiled mode a zero-disk-I/O source of truth.
 *
 * The file is GENERATED, gitignored, and regenerated on every dev/build/test
 * run (via generate-version.ts). It must never be hand-maintained — a committed
 * copy would drift from src/prompts/ silently.
 *
 * Only top-level *.md files are bundled, matching what `listBuiltinPrompts()`
 * lists (nested prompts like confirmations/*.md are consumed via their own
 * direct text imports, not via the prompt-listing command).
 */
import { readdirSync, readFileSync, writeFileSync, renameSync, statSync } from 'fs';
import { join, basename } from 'path';

const root = join(import.meta.dir, '..');
const promptsDir = join(root, 'src', 'prompts');
const outFile = join(root, 'src', 'prompts-bundle.ts');

export function generatePromptBundle(): void {
  const files = readdirSync(promptsDir)
    .filter(f => f.endsWith('.md'))
    .sort();

  const imports: string[] = [];
  const entries: string[] = [];

  files.forEach((filename, i) => {
    const ident = `p${i}`;
    imports.push(`import ${ident} from './prompts/${filename}' with { type: 'text' };`);
    // JSON.stringify the key so any special characters in filenames stay valid.
    entries.push(`  ${JSON.stringify(filename)}: ${ident},`);
  });

  const content = `// Auto-generated by scripts/generate-prompt-bundle.ts — do not edit manually.
// Maps each top-level built-in prompt filename to its inlined text content.
// Bun inlines these text imports into the compiled binary, so \`lazy system
// prompts\` and \`lazy show <prompt-code>\` work with no src/prompts/ on disk.
${imports.join('\n')}

export const PROMPT_BUNDLE: Record<string, string> = {
${entries.join('\n')}
};
`;

  // Write via temp + rename. The test preload regenerates on staleness, and an
  // e2e run starts many CLI subprocesses at once — each carrying that preload.
  // A plain writeFileSync would let one process read a half-written module
  // while another is still writing it; rename(2) is atomic, so every reader
  // sees either the old file or the complete new one.
  const tmpFile = `${outFile}.${process.pid}.tmp`;
  writeFileSync(tmpFile, content);
  renameSync(tmpFile, outFile);
}

/**
 * True when the bundle is missing, lists a different set of prompts than the
 * prompts directory holds, or is older than any prompt it should contain.
 *
 * The bundle is gitignored and generated, so a checkout keeps whatever copy it
 * generated first. It goes stale two ways:
 *   - a prompt was ADDED or edited since (merge, pull) — caught by mtime;
 *   - a prompt was DELETED or renamed (switching to a branch that lacks it) —
 *     the bundle then imports a file that does not exist, and nothing on disk
 *     got newer, so mtime alone cannot see it. The listed set is compared too.
 */
export function isPromptBundleStale(dir: string = promptsDir, bundle: string = outFile): boolean {
  let bundleMtime: number;
  let bundleSource: string;
  try {
    bundleMtime = statSync(bundle).mtimeMs;
    bundleSource = readFileSync(bundle, 'utf-8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return true;
    throw new Error(`Failed to read ${bundle}: ${(err as Error).message}`);
  }
  const onDisk = readdirSync(dir).filter(f => f.endsWith('.md')).sort();
  const listed = [...bundleSource.matchAll(/from '\.\/prompts\/([^']+\.md)'/g)].map(m => m[1]!).sort();
  if (onDisk.join('\n') !== listed.join('\n')) return true;
  return onDisk.some(f => statSync(join(dir, f)).mtimeMs > bundleMtime);
}

// Allow running directly: `bun run scripts/generate-prompt-bundle.ts`.
// `--check` writes nothing and exits 1 when the bundle is stale (native preflight).
if (import.meta.main) {
  if (process.argv.includes('--check')) process.exit(isPromptBundleStale() ? 1 : 0);
  generatePromptBundle();
  console.log(`Generated ${outFile}`);
}
