// Auto-generated by scripts/generate-version.ts / scripts/build.ts — do not edit manually
export const BUILD_TIME = 'dev';
export const BUILD_SHA = 'dev';
export const BUILD_DIRTY = false;
export const BUILD_BRANCH = 'dev';
export const BUILD_SOURCE_PATH = 'dev';
