import { describe, test, expect } from 'bun:test';
import { mkdtemp, mkdir, rm, readFile, writeFile } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { spawnSync } from '../../src/utils/spawn';

const ROOT = join(import.meta.dir, '..', '..');
const WORKFLOW = join(ROOT, '.github', 'workflows', 'build.yml');

/**
 * INVARIANT: the build workflow extracts exactly ONE version from src/version.ts.
 *
 * src/version.ts once exported two constants whose names shared a suffix:
 *
 *     export const VERSION = '0.21.1373';
 *     export const RELEASE_VERSION = '0.21.0';
 *
 * The workflow's extraction started life as `grep "VERSION = "`, which predates
 * RELEASE_VERSION and matches it too as a plain substring. That made $VERSION a
 * two-line string, and `echo "version=$VERSION" >> $GITHUB_OUTPUT` then wrote
 *
 *     version=0.21.1373
 *     0.21.0
 *
 * GitHub parses each line of that file as its own `key=value` command, so the
 * stray second line failed the whole step with `Invalid format '0.20.0'` — an
 * error naming a version string that appears nowhere in the workflow, which is
 * what made it puzzling. Nothing about the failure points at the grep.
 *
 * src/version.ts now exports VERSION and nothing else, which removes today's
 * collision but not the class of bug: the next export ending in `VERSION` would
 * reintroduce it silently. So the anchoring is still tested — against a decoy
 * file rather than against the real one, which is what keeps the test honest
 * once there is no second constant left to collide with.
 *
 * Both tests run the workflow's REAL command rather than re-implementing grep
 * semantics in JS, so they stay honest if the extraction is ever rewritten: what
 * is pinned is the output shape (exactly one line), not one particular spelling.
 */
describe('build workflow version extraction', () => {
  /** The `VERSION=$(...)` assignment, lifted verbatim out of build.yml. */
  async function extractionCommand(): Promise<string> {
    const yaml = await readFile(WORKFLOW, 'utf-8');
    const line = yaml.split('\n').find(l => l.trim().startsWith('VERSION=$('));
    if (!line) {
      throw new Error(
        `No 'VERSION=$(...)' assignment found in ${WORKFLOW}. If the extraction moved or ` +
          `was renamed, update this test to point at its new form — do not delete it.`,
      );
    }
    return line.trim();
  }

  /** Run the workflow's extraction against whatever src/version.ts is in `cwd`. */
  async function runExtraction(cwd: string): Promise<{ exitCode: number; version: string }> {
    const command = await extractionCommand();
    const result = spawnSync(['bash', '-c', `${command}\nprintf '%s' "$VERSION"`], {
      cwd,
      stdout: 'pipe',
      stderr: 'pipe',
    });
    return { exitCode: result.exitCode, version: result.stdout.toString() };
  }

  test('yields exactly one version line, so $GITHUB_OUTPUT stays well-formed', async () => {
    // version.ts is gitignored and generated; make sure it reflects package.json.
    const gen = spawnSync(['bun', 'run', 'generate:version'], {
      cwd: ROOT,
      stdout: 'pipe',
      stderr: 'pipe',
    });
    expect(gen.exitCode).toBe(0);

    const { exitCode, version } = await runExtraction(ROOT);
    expect(exitCode).toBe(0);

    // The actual bug: a second line here is what breaks the output command.
    expect(version).not.toContain('\n');
    expect(version.trim()).not.toBe('');
    // Builds off main carry an `-alpha` suffix, so it is part of the legal
    // shape — but the suffix is all that may follow the patch number.
    expect(version).toMatch(/^\d+\.\d+\.\d+(-alpha)?$/);
  });

  test('is anchored — a second export ending in VERSION cannot leak in', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'lazy-ci-version-'));
    try {
      await mkdir(join(dir, 'src'), { recursive: true });
      // A decoy in the shape of the constant that caused the original incident.
      await writeFile(
        join(dir, 'src', 'version.ts'),
        [
          "// Auto-generated by scripts/generate-version.ts — do not edit manually",
          "export const VERSION = '9.9.1234';",
          "export const RELEASE_VERSION = '9.9.0';",
          '',
        ].join('\n'),
      );

      const { exitCode, version } = await runExtraction(dir);

      expect(exitCode).toBe(0);
      expect(version).toBe('9.9.1234');
      expect(version).not.toContain('\n');
      expect(version).not.toContain('9.9.0');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
