/**
 * Local-command scaffolding is not conversation content.
 *
 * INVARIANT: Claude Code's own local-command wrappers — the `<local-command-caveat>`
 * boilerplate, a built-in slash command's `<command-name>/<command-message>/empty
 * <command-args>` block, and `<local-command-stdout>`/`<local-command-stderr>` — are
 * harness scaffolding, not something a human or an agent said. They are dropped at
 * PARSE time, so a session made of nothing else never becomes a stored conversation
 * (the existing "no parseable messages" guard in every ingest path does the skipping).
 *
 * The line is drawn at "no human-authored payload": a `<command-args>` block that is
 * NOT empty carries text the human typed (`/compact keep awareness on…`) and is kept,
 * and a real message that merely QUOTES a wrapper mid-thread is kept intact. Dropping
 * either would be curation, which import paths must never do
 * (memory: importers-are-mechanistic).
 *
 * The fixture bodies below are transcribed from real stored conversations in this
 * project's store (sessions c0f95202 and 895dffbf, 2026-09-12), including Claude
 * Code's exact leading-whitespace indentation inside the command block.
 */

import { describe, test, beforeEach, afterEach, expect } from 'bun:test';
import { mkdtempSync, rmSync } from 'fs';
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';
import { encodeProjectPath, parseConversation, extractSummary } from '../../src/import/claude-code-logs';
import { isLocalCommandScaffolding } from '../../src/import/local-command-messages';
import { reimportConversations } from '../../src/import/reimport-conversations';
import type { StoredConversation } from '../../src/storage/types';
import type { Storage } from '../../src/storage/interface';

/** The caveat Claude Code injects ahead of every local-command message. */
const CAVEAT =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. ' +
  'DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.' +
  '</local-command-caveat>';

/** A built-in slash command as Claude Code journals it, indentation and all. */
function commandBlock(name: string, args = ''): string {
  return `<command-name>/${name}</command-name>\n            <command-message>${name}</command-message>\n            <command-args>${args}</command-args>`;
}

function userLine(sessionId: string, cwd: string, n: number, text: string): string {
  return JSON.stringify({
    type: 'user',
    uuid: `${sessionId}-u${n}`,
    parentUuid: n > 0 ? `${sessionId}-u${n - 1}` : null,
    timestamp: `2026-09-12T14:0${n}:00Z`,
    sessionId,
    cwd,
    version: '2.0.0',
    gitBranch: 'main',
    message: { role: 'user', content: text },
  });
}

function assistantLine(sessionId: string, n: number, text: string): string {
  return JSON.stringify({
    type: 'assistant',
    uuid: `${sessionId}-a${n}`,
    parentUuid: `${sessionId}-u${n}`,
    timestamp: `2026-09-12T14:0${n}:05Z`,
    sessionId,
    message: {
      role: 'assistant',
      content: [{ type: 'text', text }],
      model: 'claude-fable-5-1',
      usage: { input_tokens: 10, output_tokens: 5 },
    },
  });
}

/**
 * In-memory Storage stub exposing only the conversation methods the reimport core
 * calls — the same shape `reimport-conversations.test.ts` uses, and for the same
 * reason: a real FileStorage would need the storage lock.
 */
function makeStorageStub() {
  const saved = new Map<string, StoredConversation>();
  const stub = {
    saved,
    async isConversationImported(sessionId: string): Promise<boolean> {
      return saved.has(sessionId);
    },
    async saveConversation(conv: StoredConversation): Promise<void> {
      saved.set(conv.sessionId, conv);
    },
  };
  return stub as unknown as typeof stub & Storage;
}

describe('isLocalCommandScaffolding', () => {
  test('matches the caveat, a command block, and command output, alone or together', () => {
    expect(isLocalCommandScaffolding(CAVEAT)).toBe(true);
    expect(isLocalCommandScaffolding(commandBlock('clear'))).toBe(true);
    expect(isLocalCommandScaffolding(commandBlock('model'))).toBe(true);
    expect(isLocalCommandScaffolding('<local-command-stdout>Set model to `Fable 5.1` and saved as your default for new sessions</local-command-stdout>')).toBe(true);
    expect(isLocalCommandScaffolding('<local-command-stderr>nope</local-command-stderr>')).toBe(true);
    expect(isLocalCommandScaffolding(`${CAVEAT}\n${commandBlock('clear')}`)).toBe(true);
  });

  // INVARIANT: non-empty <command-args> is text the human typed, so the message is
  // kept. Import paths bring human content in verbatim; only machine scaffolding goes.
  test('keeps a command whose args carry human-typed text', () => {
    expect(isLocalCommandScaffolding(
      commandBlock('compact', 'keep awareness on last nights run and what we are going to try to do today'),
    )).toBe(false);
  });

  // INVARIANT: the match is structural and whole-message. Prose that merely mentions a
  // wrapper — a human asking about this very behaviour — is a real message.
  test('keeps a message that only quotes a wrapper', () => {
    expect(isLocalCommandScaffolding(
      `Why is the store full of these?\n\n> ${CAVEAT}\n\nThey are not conversations at all.`,
    )).toBe(false);
    expect(isLocalCommandScaffolding(`${CAVEAT} and then I actually asked something`)).toBe(false);
    expect(isLocalCommandScaffolding('just a normal question')).toBe(false);
    expect(isLocalCommandScaffolding('')).toBe(false);
  });

  // INVARIANT: only Claude Code's BUILT-IN housekeeping commands are noise. A
  // project or custom command invoked with no arguments produces exactly the
  // same tag shape as /clear, so shape alone cannot tell them apart — and every
  // invocation recorded in this project's store has empty args, so a shape-only
  // rule would drop every custom invocation there is. Unrecognised name = kept,
  // which is correct whether or not the expanded prompt is a separate message.
  test('keeps a project or custom command, even with empty args', () => {
    expect(isLocalCommandScaffolding(commandBlock('loop'))).toBe(false);
    expect(isLocalCommandScaffolding(commandBlock('code-review'))).toBe(false);
    expect(isLocalCommandScaffolding(commandBlock('babysit-prs'))).toBe(false);
    // Including when the caveat wraps it — the caveat is written for every
    // local command, built-in or not, so it cannot decide this either.
    expect(isLocalCommandScaffolding(`${CAVEAT}\n${commandBlock('loop')}`)).toBe(false);
  });

  // The housekeeping set is matched on the NAME, not on the slash or case, and
  // an incomplete set fails harmlessly: a missing built-in is kept as a stub,
  // never dropped content.
  test('housekeeping names still match regardless of slash and case', () => {
    expect(isLocalCommandScaffolding(commandBlock('Clear'))).toBe(true);
    expect(isLocalCommandScaffolding(
      '<command-name>context</command-name>\n            <command-args></command-args>',
    )).toBe(true);
  });
});

describe('local-command sessions at ingest', () => {
  let homeDir: string;
  let dataDir: string;
  const lazyRoot = '/repo/local-commands';
  const encoded = encodeProjectPath(lazyRoot);

  /** A session containing nothing but a `/clear` — verbatim shape of real session c0f95202. */
  const NOISE_ONLY = '11111111-0000-0000-0000-00000000000a';
  /** A real conversation that merely OPENS with the caveat + `/clear` — shape of real session 895dffbf. */
  const REAL_WITH_HEADER = '22222222-0000-0000-0000-00000000000b';
  /** A real conversation quoting the caveat mid-thread. */
  const INCIDENTAL = '33333333-0000-0000-0000-00000000000c';

  const REAL_QUESTION = 'The task page does not refresh itself. How is this best managed in live systems?';
  const QUOTING_MESSAGE = `The store is full of these:\n\n> ${CAVEAT}\n\nWhy do we need to see them?`;

  beforeEach(async () => {
    homeDir = mkdtempSync(join(tmpdir(), 'lazy-localcmd-home-'));
    dataDir = mkdtempSync(join(tmpdir(), 'lazy-localcmd-data-'));
    const dir = join(homeDir, '.claude', 'projects', encoded);
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, `${NOISE_ONLY}.jsonl`), [
      userLine(NOISE_ONLY, lazyRoot, 0, CAVEAT),
      userLine(NOISE_ONLY, lazyRoot, 1, commandBlock('clear')),
    ].join('\n') + '\n');

    await writeFile(join(dir, `${REAL_WITH_HEADER}.jsonl`), [
      userLine(REAL_WITH_HEADER, lazyRoot, 0, CAVEAT),
      userLine(REAL_WITH_HEADER, lazyRoot, 1, commandBlock('clear')),
      userLine(REAL_WITH_HEADER, lazyRoot, 2, REAL_QUESTION),
      assistantLine(REAL_WITH_HEADER, 2, 'Here is how live systems do it.'),
      userLine(REAL_WITH_HEADER, lazyRoot, 3, commandBlock('model')),
      userLine(REAL_WITH_HEADER, lazyRoot, 4, '<local-command-stdout>Set model to `Fable 5.1` and saved as your default for new sessions</local-command-stdout>'),
      userLine(REAL_WITH_HEADER, lazyRoot, 5, commandBlock('compact', 'keep awareness on last nights run')),
    ].join('\n') + '\n');

    await writeFile(join(dir, `${INCIDENTAL}.jsonl`), [
      userLine(INCIDENTAL, lazyRoot, 0, QUOTING_MESSAGE),
      assistantLine(INCIDENTAL, 0, 'Those are local-command transcripts; we should not import them.'),
    ].join('\n') + '\n');
  });

  afterEach(() => {
    rmSync(homeDir, { recursive: true, force: true });
    rmSync(dataDir, { recursive: true, force: true });
  });

  const opts = () => ({ lazyRoot, dataDirAbs: dataDir, homeDirAbs: homeDir });

  // INVARIANT: a session whose entire content is local-command scaffolding is never
  // stored. It carries no human intent and no agent reasoning — it was never a
  // conversation, so importing it is not "keeping history".
  test('a local-command-only session is not stored', async () => {
    const storage = makeStorageStub();
    const report = await reimportConversations({ ...opts(), storage });

    expect(report.found).toBe(3);
    expect(report.skippedEmpty).toEqual([NOISE_ONLY]);
    expect([...storage.saved.keys()].sort()).toEqual([INCIDENTAL, REAL_WITH_HEADER].sort());
  });

  test('a real conversation is stored, without its local-command scaffolding', async () => {
    const storage = makeStorageStub();
    await reimportConversations({ ...opts(), storage });

    const stored = storage.saved.get(REAL_WITH_HEADER)!;
    const texts = stored.messages.map(m => m.text);
    expect(texts).toEqual([
      REAL_QUESTION,
      'Here is how live systems do it.',
      commandBlock('compact', 'keep awareness on last nights run'),
    ]);
    // The listing summary is the human's question, not the caveat boilerplate.
    expect(stored.summary).toBe(REAL_QUESTION);
    // Token usage is aggregated from the raw JSONL, so dropping user scaffolding
    // never changes what the session cost.
    expect(stored.stats.totalTokens).toBe(15);
  });

  test('a real conversation that quotes the caveat is kept intact', async () => {
    const storage = makeStorageStub();
    await reimportConversations({ ...opts(), storage });

    const stored = storage.saved.get(INCIDENTAL)!;
    expect(stored.messages.map(m => m.text)).toEqual([
      QUOTING_MESSAGE,
      'Those are local-command transcripts; we should not import them.',
    ]);
    expect(stored.summary).toBe(extractSummary(
      await parseConversation(encoded, INCIDENTAL, join(homeDir, '.claude', 'projects')),
    ));
  });
});
