/**
 * Cleaning local-command scaffolding out of ALREADY-STORED conversations —
 * the core behind `lazy doctor --clean-local-command-conversations`.
 *
 * INVARIANT: the REWRITE never deletes a stored conversation, and never
 * rewrites one that would be left with no content. A regression that empties
 * rows destroys history lazy cannot restore.
 *
 * INVARIANT: deleting the content-free rows is a SEPARATE function
 * (`deleteEmptiedConversations`) reached only from its own opt-in flag, and it
 * may only ever be handed `plan.emptied`. The engineer's first answer to "may
 * it delete the rows that are nothing but scaffolding" was no — only the
 * re-parse in place was authorised (raised item 77664078 on task
 * conversations-skip-local-commands). They took the deletion decision
 * themselves on 2026-09-13 (raised item 648db124 on ui-feedback-2026-09-12),
 * which is what the second function implements; the first invariant is
 * unchanged by that, since a row with content left is a rewrite, never a
 * delete.
 *
 * INVARIANT: cleaning a stored row produces exactly what importing the same raw
 * session through today's parser produces. If the two drifted, the capture
 * sweep would flip the row back and forth every time the session file changed.
 *
 * Fixture shapes are the real ones measured in this project's store: a session
 * that is nothing but caveat + `/clear` (c0f95202) and a real conversation whose
 * first two messages are that same pair (895dffbf).
 */

import { describe, test, beforeEach, afterEach, expect } from 'bun:test';
import { mkdtempSync, rmSync } from 'fs';
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';
import { encodeProjectPath } from '../../src/import/claude-code-logs';
import { reimportConversations } from '../../src/import/reimport-conversations';
import {
  applyLocalCommandCleanup,
  deleteEmptiedConversations,
  planConversationCleanup,
  planLocalCommandCleanup,
  summaryLooksLikeScaffolding,
} from '../../src/import/local-command-cleanup';
import type { StoredConversation, StoredMessage } from '../../src/storage/types';
import type { Storage } from '../../src/storage/interface';

const CAVEAT =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. ' +
  'DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.' +
  '</local-command-caveat>';

function commandBlock(name: string, args = ''): string {
  return `<command-name>/${name}</command-name>\n            <command-message>${name}</command-message>\n            <command-args>${args}</command-args>`;
}

const REAL_QUESTION = 'The task page does not refresh itself. How is this best managed in live systems?';
const ANSWER = 'Here is how live systems do it.';

/** A conversation as it was STORED before lazy filtered scaffolding at ingest. */
function legacyStored(
  sessionId: string,
  entries: Array<{ role: 'user' | 'assistant'; text: string }>,
): StoredConversation {
  const messages: StoredMessage[] = entries.map((e, i) => ({
    uuid: `${sessionId}-m${i}`,
    parentUuid: i > 0 ? `${sessionId}-m${i - 1}` : null,
    timestamp: `2026-09-12T14:0${i}:00Z`,
    role: e.role,
    text: e.text,
    model: e.role === 'assistant' ? 'claude-fable-5-1' : null,
    usage: null,
  }));
  return {
    sessionId,
    projectPath: encodeProjectPath('/repo/local-commands'),
    cwd: '/repo/local-commands',
    version: '2.0.0',
    gitBranch: 'main',
    startedAt: messages[0]?.timestamp ?? null,
    endedAt: messages[messages.length - 1]?.timestamp ?? null,
    importedAt: 1_700_000_000_000,
    summary: entries[0]?.text.split('\n')[0] ?? '(empty conversation)',
    stats: {
      messageCount: messages.length,
      userMessageCount: messages.filter(m => m.role === 'user').length,
      assistantMessageCount: messages.filter(m => m.role === 'assistant').length,
      subagentCount: 0,
      totalTokens: 15,
    },
    totalUsage: { inputTokens: 10, outputTokens: 5, cacheCreationTokens: 0, cacheReadTokens: 0 },
    messages,
    subagents: [],
  };
}

const NOISE_ONLY = legacyStored('11111111-0000-0000-0000-00000000000a', [
  { role: 'user', text: CAVEAT },
  { role: 'user', text: commandBlock('clear') },
]);

const REAL_WITH_HEADER = legacyStored('22222222-0000-0000-0000-00000000000b', [
  { role: 'user', text: CAVEAT },
  { role: 'user', text: commandBlock('clear') },
  { role: 'user', text: REAL_QUESTION },
  { role: 'assistant', text: ANSWER },
]);

const CLEAN_ALREADY = legacyStored('33333333-0000-0000-0000-00000000000c', [
  { role: 'user', text: `Why is the store full of these?\n\n> ${CAVEAT}` },
  { role: 'assistant', text: 'Because nothing filtered them at import.' },
]);

function makeStorageStub(seed: StoredConversation[] = []) {
  const saved = new Map<string, StoredConversation>(seed.map(c => [c.sessionId, c]));
  const deleted: string[] = [];
  const stub = {
    saved,
    deleted,
    async listConversations(): Promise<StoredConversation[]> {
      return [...saved.values()];
    },
    async isConversationImported(sessionId: string): Promise<boolean> {
      return saved.has(sessionId);
    },
    async saveConversation(conv: StoredConversation): Promise<void> {
      saved.set(conv.sessionId, conv);
    },
    async deleteConversation(sessionId: string): Promise<boolean> {
      deleted.push(sessionId);
      return saved.delete(sessionId);
    },
  };
  return stub as unknown as typeof stub & Storage;
}

describe('planConversationCleanup', () => {
  test('drops the scaffolding and makes the summary the human first line', () => {
    const item = planConversationCleanup(REAL_WITH_HEADER)!;
    expect(item.removed).toBe(2);
    expect(item.cleaned!.messages.map(m => m.text)).toEqual([REAL_QUESTION, ANSWER]);
    expect(item.cleaned!.summary).toBe(REAL_QUESTION);
    expect(item.cleaned!.stats.messageCount).toBe(2);
    expect(item.cleaned!.stats.userMessageCount).toBe(1);
    expect(item.cleaned!.stats.assistantMessageCount).toBe(1);
    // Timestamps follow the surviving messages, as a fresh parse computes them.
    expect(item.cleaned!.startedAt).toBe('2026-09-12T14:02:00Z');
    expect(item.cleaned!.endedAt).toBe('2026-09-12T14:03:00Z');
    // Usage is aggregated from the raw JSONL, so dropping messages never
    // changed what the session cost.
    expect(item.cleaned!.stats.totalTokens).toBe(15);
    expect(item.cleaned!.totalUsage).toEqual(REAL_WITH_HEADER.totalUsage);
  });

  // INVARIANT: a row that is nothing but scaffolding is reported and LEFT ALONE.
  // Rewriting it to an empty transcript and deleting it are both destructive,
  // and neither was authorised.
  test('reports a scaffolding-only conversation without producing a rewrite', () => {
    const item = planConversationCleanup(NOISE_ONLY)!;
    expect(item.removed).toBe(2);
    expect(item.cleaned).toBeNull();
  });

  test('leaves a conversation that merely quotes a wrapper alone', () => {
    expect(planConversationCleanup(CLEAN_ALREADY)).toBeNull();
  });

  test('never drops an assistant message that reproduces a wrapper', () => {
    const echoed = legacyStored('44444444-0000-0000-0000-00000000000d', [
      { role: 'user', text: CAVEAT },
      { role: 'assistant', text: CAVEAT },
    ]);
    const item = planConversationCleanup(echoed)!;
    expect(item.removed).toBe(1);
    expect(item.cleaned!.messages.map(m => m.role)).toEqual(['assistant']);
  });
});

describe('applyLocalCommandCleanup', () => {
  // INVARIANT: the REWRITE never deletes — deletion is its own function behind
  // its own flag, so applying the cleanup can never remove a row as a side
  // effect of being asked to clean one.
  test('rewrites only the rows with content left, and deletes nothing', async () => {
    const storage = makeStorageStub([NOISE_ONLY, REAL_WITH_HEADER, CLEAN_ALREADY]);
    const plan = planLocalCommandCleanup(await storage.listConversations());

    expect(plan.scanned).toBe(3);
    expect(plan.rewrites.map(r => r.sessionId)).toEqual([REAL_WITH_HEADER.sessionId]);
    expect(plan.emptied.map(r => r.sessionId)).toEqual([NOISE_ONLY.sessionId]);

    const result = await applyLocalCommandCleanup(storage, plan);
    expect(result.rewritten).toBe(1);
    expect(result.errors).toEqual([]);
    expect(storage.deleted).toEqual([]);
    expect(storage.saved.size).toBe(3);
    expect(storage.saved.get(NOISE_ONLY.sessionId)).toEqual(NOISE_ONLY);
    expect(storage.saved.get(CLEAN_ALREADY.sessionId)).toEqual(CLEAN_ALREADY);
    expect(storage.saved.get(REAL_WITH_HEADER.sessionId)!.summary).toBe(REAL_QUESTION);
  });

  test('is idempotent — a second run finds nothing to do', async () => {
    const storage = makeStorageStub([NOISE_ONLY, REAL_WITH_HEADER]);
    await applyLocalCommandCleanup(storage, planLocalCommandCleanup(await storage.listConversations()));

    const second = planLocalCommandCleanup(await storage.listConversations());
    expect(second.rewrites).toEqual([]);
    // The scaffolding-only row is still there, still reported, still untouched.
    expect(second.emptied.map(r => r.sessionId)).toEqual([NOISE_ONLY.sessionId]);
  });

  test('one failing row does not stop the batch', async () => {
    const storage = makeStorageStub([REAL_WITH_HEADER]);
    const plan = planLocalCommandCleanup(await storage.listConversations());
    storage.saveConversation = async () => {
      throw new Error('store is read-only');
    };

    const result = await applyLocalCommandCleanup(storage, plan);
    expect(result.rewritten).toBe(0);
    expect(result.errors.map(e => e.sessionId)).toEqual([REAL_WITH_HEADER.sessionId]);
    expect(result.errors[0].error.message).toBe('store is read-only');
  });
});

describe('deleteEmptiedConversations', () => {
  // INVARIANT: only `plan.emptied` may ever be deleted. Every row in that
  // bucket is scaffolding in EVERY stored message, so there is nothing anyone
  // said to lose; a row with one real message is a rewrite, and rewrites and
  // untouched rows must survive a deletion run byte for byte.
  test('deletes only the content-free rows, leaving rewrites and clean rows alone', async () => {
    const storage = makeStorageStub([NOISE_ONLY, REAL_WITH_HEADER, CLEAN_ALREADY]);
    const plan = planLocalCommandCleanup(await storage.listConversations());

    const seen: string[] = [];
    const result = await deleteEmptiedConversations(storage, plan, item => seen.push(item.sessionId));

    expect(result.deleted).toBe(1);
    expect(result.alreadyGone).toBe(0);
    expect(result.errors).toEqual([]);
    expect(seen).toEqual([NOISE_ONLY.sessionId]);
    expect(storage.deleted).toEqual([NOISE_ONLY.sessionId]);
    // The row with real content behind the scaffolding is untouched — it is a
    // rewrite, and this function must never reach it.
    expect(storage.saved.get(REAL_WITH_HEADER.sessionId)).toEqual(REAL_WITH_HEADER);
    expect(storage.saved.get(CLEAN_ALREADY.sessionId)).toEqual(CLEAN_ALREADY);
  });

  test('a row that is already gone is counted, not an error', async () => {
    const storage = makeStorageStub([NOISE_ONLY]);
    const plan = planLocalCommandCleanup(await storage.listConversations());
    storage.saved.delete(NOISE_ONLY.sessionId);

    const result = await deleteEmptiedConversations(storage, plan);
    expect(result).toMatchObject({ deleted: 0, alreadyGone: 1, errors: [] });
  });

  test('one failing row does not stop the batch', async () => {
    const other = legacyStored('dddd4444-4444-4444-8444-444444444444', [
      { role: 'user', text: CAVEAT },
      { role: 'user', text: commandBlock('clear') },
    ]);
    const storage = makeStorageStub([NOISE_ONLY, other]);
    const plan = planLocalCommandCleanup(await storage.listConversations());
    expect(plan.emptied.length).toBe(2);

    const real = storage.deleteConversation.bind(storage);
    storage.deleteConversation = async (sessionId: string) => {
      if (sessionId === NOISE_ONLY.sessionId) throw new Error('store is read-only');
      return real(sessionId);
    };

    const result = await deleteEmptiedConversations(storage, plan);
    expect(result.deleted).toBe(1);
    expect(result.errors.map(e => e.sessionId)).toEqual([NOISE_ONLY.sessionId]);
    expect(result.errors[0].error.message).toBe('store is read-only');
    expect(storage.saved.has(other.sessionId)).toBe(false);
  });

  test('deletes nothing when no row is scaffolding-only', async () => {
    const storage = makeStorageStub([REAL_WITH_HEADER, CLEAN_ALREADY]);
    const plan = planLocalCommandCleanup(await storage.listConversations());

    const result = await deleteEmptiedConversations(storage, plan);
    expect(result).toMatchObject({ deleted: 0, alreadyGone: 0, errors: [] });
    expect(storage.deleted).toEqual([]);
  });
});

describe('summaryLooksLikeScaffolding', () => {
  // The check reads the conversation index, where a summary is one truncated
  // line — so it matches on the OPENING tag, which survives truncation.
  test('matches a truncated caveat summary and nothing a human wrote', () => {
    expect(summaryLooksLikeScaffolding(CAVEAT.substring(0, 120))).toBe(true);
    expect(summaryLooksLikeScaffolding('<command-name>/clear</command-name>')).toBe(true);
    expect(summaryLooksLikeScaffolding(REAL_QUESTION)).toBe(false);
    expect(summaryLooksLikeScaffolding(`Why is the store full of these?  > ${CAVEAT}`)).toBe(false);
    expect(summaryLooksLikeScaffolding('')).toBe(false);
  });

  // INVARIANT: the check stays a strict SUBSET of what the remedy acts on. A
  // check reporting a row the remedy would not touch is the failure mode this
  // pair is designed against, so a summary naming a CUSTOM command — which the
  // remedy now deliberately keeps — must not be flagged either.
  test('does not flag a custom command the remedy keeps', () => {
    expect(summaryLooksLikeScaffolding('<command-name>/loop</command-name>')).toBe(false);
    expect(summaryLooksLikeScaffolding('<command-message>code-review</command-message>')).toBe(false);
    // …while the built-in housekeeping names still flag.
    expect(summaryLooksLikeScaffolding('<command-message>clear</command-message>')).toBe(true);
    expect(summaryLooksLikeScaffolding('<command-name>/model</command-name>')).toBe(true);
  });
});

/**
 * The convergence property: cleaning a stored row lands on the same content a
 * fresh import of the same raw session produces. Without it, the capture sweep
 * and this command would disagree about the same session.
 */
describe('cleanup matches what todays parser imports', () => {
  let homeDir: string;
  let dataDir: string;
  const lazyRoot = '/repo/local-commands';
  const encoded = encodeProjectPath(lazyRoot);
  const sessionId = '55555555-0000-0000-0000-00000000000e';

  beforeEach(async () => {
    homeDir = mkdtempSync(join(tmpdir(), 'lazy-cleanup-home-'));
    dataDir = mkdtempSync(join(tmpdir(), 'lazy-cleanup-data-'));
    const dir = join(homeDir, '.claude', 'projects', encoded);
    await mkdir(dir, { recursive: true });

    const line = (n: number, role: 'user' | 'assistant', text: string) =>
      JSON.stringify({
        type: role,
        uuid: `${sessionId}-m${n}`,
        parentUuid: n > 0 ? `${sessionId}-m${n - 1}` : null,
        timestamp: `2026-09-12T14:0${n}:00Z`,
        sessionId,
        cwd: lazyRoot,
        version: '2.0.0',
        gitBranch: 'main',
        message: role === 'user'
          ? { role, content: text }
          : {
              role,
              content: [{ type: 'text', text }],
              model: 'claude-fable-5-1',
              usage: { input_tokens: 10, output_tokens: 5 },
            },
      });

    await writeFile(join(dir, `${sessionId}.jsonl`), [
      line(0, 'user', CAVEAT),
      line(1, 'user', commandBlock('clear')),
      line(2, 'user', REAL_QUESTION),
      line(3, 'assistant', ANSWER),
    ].join('\n') + '\n');
  });

  afterEach(() => {
    rmSync(homeDir, { recursive: true, force: true });
    rmSync(dataDir, { recursive: true, force: true });
  });

  test('cleaned row and freshly imported row agree', async () => {
    const storage = makeStorageStub();
    await reimportConversations({ lazyRoot, dataDirAbs: dataDir, homeDirAbs: homeDir, storage });
    const fresh = storage.saved.get(sessionId)!;

    // The same session as it was stored BEFORE the ingest filter existed.
    const stale = legacyStored(sessionId, [
      { role: 'user', text: CAVEAT },
      { role: 'user', text: commandBlock('clear') },
      { role: 'user', text: REAL_QUESTION },
      { role: 'assistant', text: ANSWER },
    ]);
    const cleaned = planConversationCleanup(stale)!.cleaned!;

    expect(cleaned.messages.map(m => m.text)).toEqual(fresh.messages.map(m => m.text));
    expect(cleaned.summary).toBe(fresh.summary);
    expect(cleaned.startedAt).toBe(fresh.startedAt);
    expect(cleaned.endedAt).toBe(fresh.endedAt);
    expect(cleaned.stats.messageCount).toBe(fresh.stats.messageCount);
    expect(cleaned.stats.userMessageCount).toBe(fresh.stats.userMessageCount);
    expect(cleaned.stats.assistantMessageCount).toBe(fresh.stats.assistantMessageCount);
    expect(cleaned.stats.totalTokens).toBe(fresh.stats.totalTokens);
  });
});
