/**
 * e2e: `lazy doctor --clean-local-command-conversations` — the opt-in cleanup of
 * Claude Code local-command scaffolding stored before lazy filtered it at
 * import.
 *
 * INVARIANT: nothing is written without `--yes` or an interactive confirmation.
 *
 * INVARIANT: a conversation is NEVER deleted unless
 * `--delete-empty-local-command-conversations` was typed. `--yes` alone must
 * never imply it — `--yes` skips a prompt, it does not choose a destructive act
 * nobody asked for — and only the rows whose every stored message is
 * scaffolding are ever eligible. Deleting a stored conversation is not
 * recoverable from lazy: the raw JSONL on disk is not re-imported, because
 * today's parser drops the session as empty.
 *
 * Uses withDaemon so the rewrite takes the real route a human's run takes:
 * through the daemon's storage (RemoteStorage.saveConversation).
 *
 * Seeding is direct-to-storage on purpose: today's import path strips this
 * scaffolding, so no ingest surface can produce the rows this command exists to
 * fix. The shapes are the ones measured in this project's live store — a
 * session that is nothing but caveat + `/clear`, and a real conversation whose
 * first two messages are that same pair.
 */

import { describe, test, beforeEach, afterEach, expect } from 'bun:test';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { setupTestLazy, type TestContext } from '../helpers/setup';
import { writeConversationFile, storageDirFor } from '../helpers/storage';
import {
  expectSuccess,
  expectFailure,
  expectOutput,
  expectError,
  expectOutputExcludes,
} from '../helpers/assertions';

const CAVEAT =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. ' +
  'DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.' +
  '</local-command-caveat>';

const CLEAR_BLOCK =
  '<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>';

const NOISE_ONLY = 'aaaa1111-1111-4111-8111-111111111111';
const REAL_WITH_HEADER = 'bbbb2222-2222-4222-8222-222222222222';
const UNAFFECTED = 'cccc3333-3333-4333-8333-333333333333';

const REAL_QUESTION = 'How is a live task page best kept up to date?';

function conversation(sessionId: string, messages: Array<{ role: 'user' | 'assistant'; text: string }>) {
  return {
    sessionId,
    projectPath: '-tmp-project',
    cwd: '/tmp/project',
    version: '2.0.0',
    gitBranch: 'main',
    startedAt: '2026-08-30T10:00:00.000Z',
    endedAt: '2026-08-30T11:30:00.000Z',
    importedAt: Date.now(),
    // What the listing shows today: the first user message, scaffolding and all.
    summary: messages[0].text.split('\n')[0],
    stats: {
      messageCount: messages.length,
      userMessageCount: messages.filter(m => m.role === 'user').length,
      assistantMessageCount: messages.filter(m => m.role === 'assistant').length,
      subagentCount: 0,
      totalTokens: 1234,
    },
    totalUsage: { inputTokens: 100, outputTokens: 200, cacheCreationTokens: 0, cacheReadTokens: 0 },
    messages: messages.map((m, i) => ({
      uuid: `${sessionId}-m${i}`,
      parentUuid: i > 0 ? `${sessionId}-m${i - 1}` : null,
      timestamp: `2026-08-30T10:0${i}:00.000Z`,
      role: m.role,
      text: m.text,
      model: m.role === 'assistant' ? 'claude-opus-5' : null,
      usage: null,
    })),
    subagents: [],
  };
}

function storedPath(root: string, sessionId: string): string {
  return join(storageDirFor(root), 'conversations', `${sessionId}.json`);
}

function storedExists(root: string, sessionId: string): boolean {
  return existsSync(storedPath(root, sessionId));
}

function readStored(root: string, sessionId: string): Record<string, any> {
  return JSON.parse(
    readFileSync(join(storageDirFor(root), 'conversations', `${sessionId}.json`), 'utf-8'),
  );
}

describe('lazy doctor --clean-local-command-conversations', () => {
  let ctx: TestContext;

  beforeEach(async () => {
    ctx = await setupTestLazy({ withDaemon: true });

    writeConversationFile(ctx.root, conversation(NOISE_ONLY, [
      { role: 'user', text: CAVEAT },
      { role: 'user', text: CLEAR_BLOCK },
    ]));
    writeConversationFile(ctx.root, conversation(REAL_WITH_HEADER, [
      { role: 'user', text: CAVEAT },
      { role: 'user', text: CLEAR_BLOCK },
      { role: 'user', text: REAL_QUESTION },
      { role: 'assistant', text: 'Push the change to the page instead of polling for it.' },
    ]));
    writeConversationFile(ctx.root, conversation(UNAFFECTED, [
      { role: 'user', text: 'Why is the store full of caveat blocks?' },
      { role: 'assistant', text: 'Nothing filtered them at import.' },
    ]));
  });

  afterEach(async () => {
    await ctx.cleanup();
  });

  // INVARIANT: a preview run must not touch the store.
  test('lists what it would do and changes NOTHING without --yes', async () => {
    const preview = await ctx.lazy(['doctor', '--clean-local-command-conversations']);
    expectSuccess(preview);
    expectOutput(preview, 'bbbb2222');
    expectOutput(preview, 'would become');
    expectOutput(preview, REAL_QUESTION);
    // The scaffolding-only row is reported separately, never as a rewrite, and
    // the run that was not asked to delete says so and names the flag.
    expectOutput(preview, 'aaaa1111');
    expectOutput(preview, 'These are left exactly as they are');
    expectOutput(preview, '--delete-empty-local-command-conversations');
    // A conversation with no scaffolding is not listed at all.
    expectOutputExcludes(preview, 'cccc3333');

    expect(readStored(ctx.root, REAL_WITH_HEADER).messages.length).toBe(4);
    expect(readStored(ctx.root, REAL_WITH_HEADER).summary).toContain('local-command-caveat');
  });

  test('--dry-run lists and stops', async () => {
    const dry = await ctx.lazy(['doctor', '--clean-local-command-conversations', '--dry-run']);
    expectSuccess(dry);
    expectOutput(dry, 'Dry run — nothing changed');
    expect(readStored(ctx.root, REAL_WITH_HEADER).messages.length).toBe(4);
  });

  test('--yes rewrites the affected rows, deletes nothing, and is idempotent', async () => {
    const run = await ctx.lazy(['doctor', '--clean-local-command-conversations', '--yes']);
    expectSuccess(run);
    expectOutput(run, 'Cleaned 1 of 1 conversation(s).');

    const cleaned = readStored(ctx.root, REAL_WITH_HEADER);
    expect(cleaned.messages.map((m: any) => m.text)).toEqual([
      REAL_QUESTION,
      'Push the change to the page instead of polling for it.',
    ]);
    expect(cleaned.summary).toBe(REAL_QUESTION);
    expect(cleaned.stats.messageCount).toBe(2);
    // Token totals come from the raw session, not from the kept messages.
    expect(cleaned.stats.totalTokens).toBe(1234);

    // INVARIANT: the scaffolding-only row is still there, byte for byte.
    const untouched = readStored(ctx.root, NOISE_ONLY);
    expect(untouched.messages.length).toBe(2);
    // And so is the conversation that never had scaffolding.
    expect(readStored(ctx.root, UNAFFECTED).messages.length).toBe(2);

    const again = await ctx.lazy(['doctor', '--clean-local-command-conversations', '--yes']);
    expectSuccess(again);
    expectOutput(again, 'Nothing to rewrite');
    expect(readStored(ctx.root, REAL_WITH_HEADER).messages.length).toBe(2);
  });

  // The remedy is only reachable if doctor says it is needed — a flag nobody is
  // told about cleans nothing. The check counts off the conversation index, so
  // it sees the two rows whose SUMMARY is scaffolding.
  test('the doctor sweep warns and names the flag', async () => {
    const report = await ctx.lazy(['doctor']);
    expectOutput(report, 'list Claude Code local-command scaffolding');
    expectOutput(report, 'lazy doctor --clean-local-command-conversations');
  });

  test('says so plainly when the store is already clean', async () => {
    expectSuccess(await ctx.lazy(['doctor', '--clean-local-command-conversations', '--yes']));
    // Remove the two rows the command reports on, leaving only clean history.
    writeConversationFile(ctx.root, conversation(NOISE_ONLY, [
      { role: 'user', text: 'A real question after all.' },
    ]));

    const result = await ctx.lazy(['doctor', '--clean-local-command-conversations']);
    expectSuccess(result);
    expectOutput(result, 'nothing to clean up');
  });

  // INVARIANT: `--yes` skips a prompt; it does not opt into deletion. A run that
  // was never given the delete flag must leave every content-free row in place,
  // however emphatically it was told to proceed.
  test('--yes alone never deletes the content-free rows', async () => {
    const run = await ctx.lazy(['doctor', '--clean-local-command-conversations', '--yes']);
    expectSuccess(run);
    expectOutputExcludes(run, 'Deleted');
    expect(storedExists(ctx.root, NOISE_ONLY)).toBe(true);
    expect(readStored(ctx.root, NOISE_ONLY).messages.length).toBe(2);
  });

  // INVARIANT: the delete flag is a modifier on the cleanup, not a remedy of its
  // own — on its own it would be a delete with no listing in front of it.
  test('the delete flag alone is refused, and deletes nothing', async () => {
    const run = await ctx.lazy(['doctor', '--delete-empty-local-command-conversations']);
    expectFailure(run);
    expectError(run, 'only applies to --clean-local-command-conversations');
    expect(storedExists(ctx.root, NOISE_ONLY)).toBe(true);
  });

  // Non-interactive without consent: the listing is printed, the refusal names
  // how to proceed, and the store is untouched.
  test('refuses to delete non-interactively without --yes', async () => {
    const run = await ctx.lazy([
      'doctor', '--clean-local-command-conversations', '--delete-empty-local-command-conversations',
    ]);
    expectSuccess(run);
    // Listed with its session id and start time before anything is asked.
    expectOutput(run, 'aaaa1111');
    expectOutput(run, '2026-08-30 10:00');
    expectOutput(run, 'would be DELETED');
    expectOutput(run, 'nothing was changed');
    expect(storedExists(ctx.root, NOISE_ONLY)).toBe(true);
  });

  test('--dry-run with the delete flag lists the rows and deletes nothing', async () => {
    const dry = await ctx.lazy([
      'doctor', '--clean-local-command-conversations',
      '--delete-empty-local-command-conversations', '--dry-run',
    ]);
    expectSuccess(dry);
    expectOutput(dry, 'would be DELETED');
    expectOutput(dry, 'Dry run — nothing changed');
    expect(storedExists(ctx.root, NOISE_ONLY)).toBe(true);
  });

  test('the flag plus --yes deletes exactly the content-free rows, and is idempotent', async () => {
    const run = await ctx.lazy([
      'doctor', '--clean-local-command-conversations',
      '--delete-empty-local-command-conversations', '--yes',
    ]);
    expectSuccess(run);
    // The caveat the human must see: this is not undone by a re-import.
    expectOutput(run, 'reimport-conversations');
    expectOutput(run, 'Deleted 1 of 1 content-free conversation(s).');

    expect(storedExists(ctx.root, NOISE_ONLY)).toBe(false);
    // The row with real content behind the scaffolding was cleaned, not deleted.
    expect(storedExists(ctx.root, REAL_WITH_HEADER)).toBe(true);
    expect(readStored(ctx.root, REAL_WITH_HEADER).summary).toBe(REAL_QUESTION);
    // And the conversation that never had scaffolding is untouched.
    expect(readStored(ctx.root, UNAFFECTED).messages.length).toBe(2);

    const again = await ctx.lazy([
      'doctor', '--clean-local-command-conversations',
      '--delete-empty-local-command-conversations', '--yes',
    ]);
    expectSuccess(again);
    expectOutput(again, 'nothing to clean up');
  });
});
